#!/usr/bin/env python3
"""package·profile 선언에서 시스템 카탈로그 문서를 생성한다.

package.yaml과 profile이 이미 결정적으로 알고 있는 사실(version, 소유 책임, skill, hook)을
사람이 Markdown에 옮겨 적지 않기 위한 generator다. `--check`는 커밋된 문서가 선언과 같은지만
확인하고 파일을 쓰지 않는다.

Example:
    python3 tools/generate-catalog.py
    python3 tools/generate-catalog.py --check
"""

import difflib
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "lib"))

import engsys_yaml  # noqa: E402

SYSTEM_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUTPUT_PATH = os.path.join(SYSTEM_ROOT, "docs", "generated", "system-catalog.md")
RELATIVE_OUTPUT = "docs/generated/system-catalog.md"


def main(argv):
    check_only = "--check" in argv
    unknown = [argument for argument in argv if argument != "--check"]
    if unknown:
        print("usage: generate-catalog.py [--check]", file=sys.stderr)
        return 2

    content = _render(engsys_yaml.load(os.path.join(SYSTEM_ROOT, "system.yaml")))
    if not check_only:
        os.makedirs(os.path.dirname(OUTPUT_PATH), exist_ok=True)
        with open(OUTPUT_PATH, "w", encoding="utf-8") as handle:
            handle.write(content)
        print("Generated %s" % RELATIVE_OUTPUT)
        return 0

    if not os.path.isfile(OUTPUT_PATH):
        print("FAIL %s is missing; run python3 tools/generate-catalog.py" % RELATIVE_OUTPUT, file=sys.stderr)
        return 1
    with open(OUTPUT_PATH, "r", encoding="utf-8") as handle:
        current = handle.read()
    if current == content:
        print("ok %s matches package declarations" % RELATIVE_OUTPUT)
        return 0

    print("FAIL %s is stale; run python3 tools/generate-catalog.py" % RELATIVE_OUTPUT, file=sys.stderr)
    diff = difflib.unified_diff(
        current.splitlines(True), content.splitlines(True), "committed", "generated"
    )
    sys.stderr.writelines(diff)
    return 1


def _render(catalog):
    system = catalog.get("system", {})
    lines = [
        "<!-- Generated by tools/generate-catalog.py. Edit package.yaml or profiles instead. -->",
        "",
        "# System catalog",
        "",
        "- system: `%s` %s" % (system.get("name", "?"), system.get("version", "?")),
        "- plugin: `%s`" % system.get("plugin", "?"),
        "",
        "## Packages",
        "",
    ]
    for name in sorted(catalog.get("packages", {})):
        lines.extend(_render_package(name, catalog["packages"][name]))
    lines.extend(["## Profiles", ""])
    for name in sorted(catalog.get("profiles", {})):
        lines.extend(_render_profile(name, catalog["profiles"][name]))
    return "\n".join(lines).rstrip("\n") + "\n"


def _render_package(name, entry):
    manifest_path = os.path.join(SYSTEM_ROOT, entry["path"], "package.yaml")
    package = engsys_yaml.load(manifest_path)["package"]
    lines = [
        "### %s" % name,
        "",
        "- version: `%s` (%s)" % (package.get("version", "?"), package.get("status", "?")),
        "- path: `%s`" % entry["path"],
        "",
        "소유 책임:",
        "",
    ]
    for responsibility in package.get("owns") or []:
        lines.append("- %s" % responsibility)
    lines.append("")

    adapter = package.get("claude-code") or {}
    skills = adapter.get("skills") or []
    lines.append("Claude Code skill:")
    lines.append("")
    if skills:
        for skill in skills:
            lines.append("- `%s` (`%s/%s`)" % (os.path.basename(skill), entry["path"], skill))
    else:
        lines.append("- 없음")
    lines.append("")

    hooks = adapter.get("hooks") or []
    lines.append("Claude Code hook:")
    lines.append("")
    if hooks:
        for hook in hooks:
            matcher = hook.get("matcher")
            scope = "matcher `%s`" % matcher if matcher else "모든 호출"
            lines.append(
                "- `%s` %s → `%s` (timeout %ss)"
                % (hook["event"], scope, hook["command"], hook["timeout"])
            )
    else:
        lines.append("- 없음")
    lines.append("")
    return lines


def _render_profile(name, entry):
    profile = engsys_yaml.load(os.path.join(SYSTEM_ROOT, entry["path"]))["profile"]
    lines = [
        "### %s" % name,
        "",
        "%s" % profile.get("description", ""),
        "",
        "package:",
        "",
    ]
    for package in entry.get("packages") or []:
        lines.append("- `%s`" % package)
    lines.append("")
    return lines


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
